# Olist Dataset EDA

In [31]:
import pandas as pd
from pathlib import Path

DATA_PATH = Path('../data/raw/')
customers = pd.read_csv(DATA_PATH / 'olist_customers_dataset.csv')
location = pd.read_csv(DATA_PATH / 'olist_geolocation_dataset.csv')
order_items = pd.read_csv(DATA_PATH / 'olist_order_items_dataset.csv')
order_payments = pd.read_csv(DATA_PATH / 'olist_order_payments_dataset.csv')
order_reviews = pd.read_csv(DATA_PATH / 'olist_order_reviews_dataset.csv')
orders = pd.read_csv(DATA_PATH / 'olist_orders_dataset.csv')
products = pd.read_csv(DATA_PATH / 'olist_products_dataset.csv')
sellers = pd.read_csv(DATA_PATH / 'olist_sellers_dataset.csv')
category = pd.read_csv(DATA_PATH / 'product_category_name_translation.csv')

In [7]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 3.8+ MB

In [79]:
customers.shape

(99441, 5)

In [12]:
location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 38.2+ MB

In [78]:
location.shape

(1000163, 5)

In [23]:
location.duplicated().value_counts()

False    738332
True     261831
Name: count, dtype: int64

In [29]:
location.duplicated(subset=['geolocation_zip_code_prefix', 'geolocation_city', 'geolocation_state']).value_counts()

True     972251
False     27912
Name: count, dtype: int64

In [32]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 6.0+ MB

In [80]:
order_items.shape

(112650, 7)

In [34]:
order_items['order_id'].nunique()

98666

In [40]:
order_items.duplicated(subset=['order_id', 'order_item_id']).value_counts()

False    112650
Name: count, dtype: int64

In [41]:
order_payments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 4.0+ MB

In [81]:
order_payments.shape

(103886, 5)

In [42]:
order_payments.nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [45]:
order_payments['payment_sequential'].value_counts()

payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
17        6
19        6
18        6
16        6
20        4
21        4
22        3
24        2
25        2
26        2
23        2
27        1
28        1
29        1
Name: count, dtype: int64

In [60]:
order_payments.duplicated(subset=['order_id', 'payment_sequential']).value_counts()

False    103886
Name: count, dtype: int64

In [62]:
order_payments['payment_installments'].value_counts(ascending=True)

payment_installments
22        1
23        1
0         2
21        3
16        5
17        8
14       15
13       16
20       17
24       18
11       23
18       27
15       74
12      133
9       644
7      1626
6      3920
8      4268
5      5239
10     5328
4      7098
3     10461
2     12413
1     52546
Name: count, dtype: int64

In [54]:
order_payments.groupby('order_id').agg({'payment_sequential': 'min'}).value_counts()

payment_sequential
1                     99360
2                        80
Name: count, dtype: int64

In [58]:
order_payments.groupby('order_id').agg({'payment_sequential': 'count', 'payment_type': 'count'})

                                  payment_sequential  payment_type
order_id
00010242fe8c5a6d1ba2dd792cb16214                   1             1
00018f77f2f0320c557190d7a144bdd3                   1             1
000229ec398224ef6ca0657da4fc703e                   1             1
00024acbcdf0a6daa1e931b038114c75                   1             1
00042b26cf59d7ce69dfabb4e55b4fd9                   1             1
...                                              ...           ...
fffc94f6ce00a00581880bf54a75a037                   1             1
fffcd46ef2263f404302a634eb57f7eb                   1             1
fffce4705a9662cd70adb13d4a31832d                   1             1
fffe18544ffabc95dfada21779c9644f                   1             1
fffe41c64501cc87c801fd61db3f6244                   1             1

[99440 rows x 2 columns]

In [57]:
grouped = order_payments.groupby('order_id').agg({'payment_sequential': 'min', 'payment_type': 'count'})
grouped[grouped['payment_sequential'] == 2]

                                  payment_sequential  payment_type
order_id
00ac05fe0fc047c54418098eb64e3aaa                   2             1
056c68d093c100017aab1f00f260705c                   2             1
0668d086b3ae41adde3aed3dacbc8fae                   2             1
0a7d898c6305101e69e9f5a05cd0130d                   2             1
0d0e88a418636d40ea780339701db49c                   2             1
...                                              ...           ...
f0f94b7c7548150f33f5d9e7597d396f                   2             1
f17a58e669a7f4cf7a7f227899f8abf7                   2             1
f5691c2b1ca263490374d13d020bd950                   2             1
fce3db7092e1f432d0ec790414b6a5e4                   2             1
fe49c4a1416840f8ed6bd36daac85aae                   2             1

[80 rows x 2 columns]

In [64]:
order_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [82]:
order_reviews.shape

(99224, 7)

In [63]:
order_reviews.nunique()

review_id                  98410
order_id                   98673
review_score                   5
review_comment_title        4527
review_comment_message     36159
review_creation_date         636
review_answer_timestamp    98248
dtype: int64

In [69]:
order_reviews.duplicated(subset=['review_id', 'order_id']).value_counts()

False    99224
Name: count, dtype: int64

In [71]:
order_reviews[order_reviews.duplicated(subset=['review_id'])]

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
3317,3242cc306a9218d0377831e175d62fbf,9c5bfba7de6a4abbb6ba0baab78d1622,5,NaN,Ótimo,2017-07-21 00:00:00,2017-07-22 01:06:37
5719,308316408775d1600dad81bd3184556d,3fe4dbcdb046a475dbf25463c1ca78bd,5,NaN,Ajudem a rastrear uma das 3 prateleiras que fa...,2017-09-07 00:00:00,2017-09-11 09:58:09
7213,8ee90ac383cf825bb7f4756130d4e74a,75d5d3d16567a27eefc5752aeb063072,5,NaN,recomendo,2017-05-30 00:00:00,2017-06-02 18:16:17
7805,d433c252647c51309432ca0b763f969b,191abde9c3bf77d1ce67d100d8db6d15,1,NaN,NaN,2017-09-03 00:00:00,2017-09-06 16:11:00
9013,03a6a25db577d0689440933055111897,3fde8b7313af6b37b84b5c7594d7add0,5,NaN,Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...,2017-12-15 00:00:00,2017-12-16 01:32:18
...,...,...,...,...,...,...,...
99108,2c6c08892b83ba4c1be33037c2842294,42ae1967f68c90bb325783ac55d761ce,4,NaN,"Chegou um pouco amassada, mas nada de mais, e ...",2017-07-03 00:00:00,2017-07-05 19:06:59
99124,6ec93e77f444e0b1703740a69122e35d,e1fdc6e9d1ca132377e862593a7c0bd4,5,NaN,Vendedor compromisso do vou o cliente,2017-10-07 00:00:00,2017-10-07 19:47:11
99164,2afe63a67dfd99b3038f568fb47ee761,c5334d330e36d2a810a7a13c72e135ee,5,NaN,"Muito bom, produto conforme anunciado, entrega...",2018-03-03 00:00:00,2018-03-04 22:56:47
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
99178,44d1e9165ec54b1d89d33594856af859,a7dbcf5043158d6fa72859eead2f3d10,4,NaN,NaN,2017-05-24 00:00:00,2017-05-24 23:15:21

In [72]:
order_reviews[order_reviews['review_id'] == '3242cc306a9218d0377831e175d62fbf']

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
1009,3242cc306a9218d0377831e175d62fbf,711246846695fa895c1776f0ddc30b20,5,NaN,Ótimo,2017-07-21 00:00:00,2017-07-22 01:06:37
3317,3242cc306a9218d0377831e175d62fbf,9c5bfba7de6a4abbb6ba0baab78d1622,5,NaN,Ótimo,2017-07-21 00:00:00,2017-07-22 01:06:37

In [11]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [83]:
orders.shape

(99441, 8)

In [35]:
orders['order_id'].nunique()

99441

In [73]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 2.3+ MB

In [84]:
products.shape

(32951, 9)

In [74]:
products.nunique()

product_id                    32951
product_category_name            73
product_name_lenght              66
product_description_lenght     2960
product_photos_qty               19
product_weight_g               2204
product_length_cm                99
product_height_cm               102
product_width_cm                 95
dtype: int64

In [75]:
sellers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 96.8+ KB

In [77]:
sellers.shape

(3095, 4)

In [76]:
sellers.nunique()

seller_id                 3095
seller_zip_code_prefix    2246
seller_city                611
seller_state                23
dtype: int64

In [85]:
category.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [86]:
category.shape

(71, 2)

In [88]:
category.nunique()

product_category_name            71
product_category_name_english    71
dtype: int64